### ISSUE TITLE
Unable to install with python3.7

### ISSUE THREAD

**Issue by Jawtoch** [DistAlgo/distalgo#36]
I tried, with some colleagues to install pyDistAlgo with `python3.7`.
As mentionned in the requirements, it should work.

I ran the following command:
```
me@mycomputer:~$ pip3.7 install pyDistAlgo
```

and getting results: (full output [here](https://pastebin.com/xSXQDTt8))
```
Collecting pyDistAlgo
  Using cached pyDistAlgo-1.0.14.tar.gz (460 kB)
Building wheels for collected packages: pyDistAlgo
  Building wheel for pyDistAlgo (setup.py) ... error
…
ERROR: Failed building wheel for pyDistAlgo
  Running setup.py clean for pyDistAlgo
Failed to build pyDistAlgo
Installing collected packages: pyDistAlgo
    Running setup.py install for pyDistAlgo ... error
…
File "/tmp/pip-install-m20wjka9/pydistalgo_a9288be70037441ca6212a6ebe18fc55/da/tools/unparse.py", line 353, in _If
        self.dispatch(t.test)
      File "/tmp/pip-install-m20wjka9/pydistalgo_a9288be70037441ca6212a6ebe18fc55/da/tools/unparse.py", line 119, in dispatch
        meth = getattr(self, "_"+tree.__class__.__name__)
    AttributeError: 'Unparser' object has no attribute '_NoneType'
```

We have tried on macOS 11, on three differents computer, and with the `python:3.7` docker image, with no success.
I succeed with the `python:3.6` docker image

**Comment by yanhongliu** [comment]
Hi, please see README, under Installation Option 1,
Installing pre-release versions using pip

**Comment by Jawtoch** [comment]
Working with `python3.7`, but I've got pyDistAlgo `1.1.0b15`.
Still unable to install <ins>stable</ins> release, such as `1.0.14`, as I've got the same error.

**Comment by yanhongliu** [comment]
1.1.0b15 is stable.  It has been used extensively.

**Comment by Jawtoch** [comment]
Why naming it as beta 15 ?

**Comment by yanhongliu** [comment]
Because it's not fun to deal with Python AST changes... if you know what that means.
